### ISSUE TITLE
Language pack instructions

### ISSUE THREAD

**Issue by hryamzik** [MarSoft/pebble-firmware-utils#10]
Can we have some instructions on building language packs, please? I miss some unicode chars in a "Latin-based + Cyrillic-based" one and would like to add them. (Weather app sends notifications with narrows).

**Comment by MarSoft** [comment]
Hello. Unfortunately I cannot make a detailed guide because didn't learn it fully yet.
Basically you will have to tear down existing langpack using `unpackFirmware.py`, then unpack its fonts using `extract_codepoints.py` script, then insert your new chars & add their metadata to .json file, then repack using `fontgen.py`, then rebuild language pack with `pbpack.py` or `packResources.py`.

**Comment by hryamzik** [comment]
I'll give it a try, thanks!
