### ISSUE TITLE
RTL language

### ISSUE THREAD

**Issue by BorisKozo** [MarSoft/pebble-firmware-utils#11]
Is there a way to show RTL languages such as Hebrew as RTL?
I installed the language pack and everything is reversed :)

**Comment by Alexeiaven** [comment]
the same. pack rus + heb - hebrew is reversed, russian is OK. Pebble time in English

**Comment by TomaiMoneyhon** [comment]
Hello i would also love this to be available. But for now if you want you can use the "notifications for pebble" which kind of fixes this.

**Comment by BorisKozo** [comment]
What is "notifications for pebble" and how does it fix the RTL problem?

**Comment by TomaiMoneyhon** [comment]
sorry i got the name wrong. it's "notification center for pebble" (https://play.google.com/store/apps/details?id=com.matejdro.pebblenotificationcenter)

what it does is that it replaces the default pebble notification system with this app (you must add it as a notification manager in the phones settings and remove pebble from there).

after installing hebrew it will recognize the hebrew and automatically position the text so that it's readable. 

this solution is obviously not perfect (the text shown is inconsistant in each app and emoji can confuse the text) 

but its the best solution i found for now....

Also it's important to note that i'd recommend also installing "Dialer for pebble" (https://play.google.com/store/apps/details?id=com.matejdro.pebbledialer&hl=en) because the system notifications of the pebble will be disabled.

**Comment by Alexeiaven** [comment]
I have already learned to read hebrew left-to-right :) It easier for me
than you suggestions

2015-12-24 11:50 GMT+02:00 Tomai <notifications@github.com>:

> sorry i got the name wrong. it's "notification center for pebble" (
> https://play.google.com/store/apps/details?id=com.matejdro.pebblenotificationcenter
> )
>
> what it does is that it replaces the default pebble notification system
> with this app (you must add it as a notification manager in the phones
> settings and remove pebble from there).
>
> after installing hebrew it will recognize the hebrew and automatically
> position the text so that it's readable.
>
> this solution is obviously not perfect (the text shown is inconsistant in
> each app and emoji can confuse the text)
>
> but its the best solution i found for now....
>
> Also it's important to note that i'd recommend also installing "Dialer for
> pebble" (
> https://play.google.com/store/apps/details?id=com.matejdro.pebbledialer&hl=en)
> because the system notifications of the pebble will be disabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarSoft/pebble-firmware-utils/issues/11#issuecomment-167079281>
> .
>



-- 
Best regards,
Alexei Aven
*אלכסיי אבן*

tel. 0544 629316

www.linkedin.com/in/alexeieven

http://alexeiaven.500px.com/

**Comment by elichai** [comment]
Anything new in this matter?

**Comment by BorisKozo** [comment]
Don't hold your breath...

**Comment by MarSoft** [comment]
Hello everybody. I do not plan to implement this feature anymore (at least for now), because another project already implemented it.
Please head to [elbbeP project page](https://elbbep.cpfx.ca/) — they implemented proper RTL support, and they probably did it much better than I could do, because they do use RTL in their life.
Also, when you use elbbeP firmware, you still can install custom language pack instead of theirs one. Language packs can be generated with my tool https://pebware.herokuapp.com/langs or with any other method. This is important if you want to have support for several languages, e.g. Hebrew+Russian.

**Comment by BorisKozo** [comment]
Semion,

I just wanted to say big Thank You for all the work you put into this project. It is not obvious that people spend their free time to help random strangers on the internet with OSS projects.

I will try elbbeP as you suggested.

**Comment by MarSoft** [comment]
Actually this project is still not dead, I have some ideas on new features, like enhanced quicklaunch capability, and will eventually implement them.
