### ISSUE TITLE
Add Russian language to translations

### ISSUE THREAD

**Issue by kryltsov** [MarSoft/pebble-firmware-utils#19]
Please add it and I will translate. I specifically interested in ability to see text messages I get in Russian.

Thanks
Igor

**Comment by MarSoft** [comment]
Hello. It is already there for a long time, it was the first language added
:-)
Do you miss it somewhere?

чт, 25 мая 2017 г., 13:02 Igor Kryltsov <notifications@github.com>:

**Comment by kryltsov** [comment]
Am I looking at a wrong page - https://poeditor.com/join/project/75a3704f7d1dea8a80071c0ad111fcc8?
Basically I am happy with UI being English but being not able to read Skype and SMS messages in Russian when they pop up on Pebble sucks. If this is already done - what I should be doing to fix it?

Thanks

**Comment by MarSoft** [comment]
Probably Russian is not shown because it is 100% complete.
Just go to http://pebware.herokuapps.com/ and build a language pack for
you. Choose Russian translation if you want, or no translation to just have
Russian characters support.
BTW, Russian characters (Cyrillic) is also supported officially for a long
time, and is available in Pebble app settings -> Language.

пт, 26 мая 2017 г., 9:44 Igor Kryltsov <notifications@github.com>:

**Comment by kryltsov** [comment]
I fixed it. Here are the steps:

Go to mega.nz and create an account (make sure to verify email)
Download and install mega.nz app on your phone
Follow one of the mega.nz links for a .pbz or a .pbl file in your browser
https://mega.co.nz/#!Qd8RWDbb!PRscY6EucF8Rge69uqIvzLx4KvElOe3-m187Vi2rhtM
Once you are redirected to mega.nz - select "Import to your cloud drive" (gray button on the right)
Open mega.nz app on your iPhone
Select the downloaded file
Click the share button in the top right corner and select "Copy to Pebble Time"
Follow along with the installation on your watch
--------------
When done you will get your watch using English byt it will start showing Russian messages properly.

Thanks for your help!
